import { ArrowRight, CornerDownRight, X } from 'lucide-react'
import { motion } from 'framer-motion'
import type { ArchiveData, ConnectionNode } from '../data/types'
import { ALIGNMENT_NOTE } from '../data/types'
import { Eyebrow, Panel, Tag } from './Primitives'

interface Props { data: ArchiveData; node: ConnectionNode | null; onClose: () => void }

export function InvestigationPanel({ data, node, onClose }: Props) {
  if (!node) return null
  const stat = node.id === 'night' ? `${data.story.spotify.nightShare}% of listening traces land between 00:00 and 06:00` : node.id === 'repeat' ? `${data.spotifyTracks[0]?.value ?? 207} recorded plays for the top repeated track` : node.id === 'session' ? `${Math.floor(data.story.spotify.longestSessionMinutes / 60)}h ${data.story.spotify.longestSessionMinutes % 60}m inactivity-bounded session` : node.id === 'subscription' ? `${data.story.household.subscriptions} subscription-category records` : `${data.story.india.duplicateShare}% duplicate extras in the supplied India rows`
  return <motion.aside className="investigation-panel" data-testid="investigation-panel" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 20 }} role="dialog" aria-modal="true" aria-labelledby="investigation-title"><div className="investigation-head"><div><Eyebrow tone={node.kind === 'ANOMALY' ? 'coral' : 'cyan'}>{node.kind} / SELECTED TRACE</Eyebrow><h2 id="investigation-title">{node.label}</h2></div><button data-testid="investigation-close" onClick={onClose} aria-label="Close investigation panel"><X size={18} /></button></div><div className="investigation-stat"><span>OBSERVED SIGNAL</span><strong>{stat}</strong></div><p className="investigation-copy">{node.description}</p><p className="investigation-disclaimer">Shared temporal density detected. Analytical alignment only — non-causal data framing enforced.</p><div className="evidence-grid" aria-label="Side-by-side source evidence">{node.datasets.map((dataset) => <Panel className="evidence-card" data-testid={`evidence-${dataset}`} key={dataset}><Tag tone={dataset === 'india' ? 'coral' : dataset === 'household' ? 'amber' : 'cyan'}>{dataset.toUpperCase()}</Tag><strong>{dataset === 'spotify' ? data.manifest.sources.spotify.rows.toLocaleString() : dataset === 'household' ? data.manifest.sources.household.rows.toLocaleString() : data.manifest.sources.india.rows.toLocaleString()}</strong><small>source traces indexed</small><ArrowRight size={14} /></Panel>)}</div><div className="investigation-note"><CornerDownRight size={15} /><span>{ALIGNMENT_NOTE}</span></div><button className="text-link" data-testid="investigation-return" onClick={onClose}>RETURN TO ARCHIVE <ArrowRight size={14} /></button></motion.aside>
}
